default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost # or the correct hostname/IP
  username: citizix_user
  password: S3cret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_hotwire

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
